baseURL = 'https://127.0.0.1:1313/'
languageCode = 'en-us'
title = 'Orthopraxis'
theme = 'skeleton'

[[menu.main]]
name = 'Home'
pageRef = '/'
title = 'return to home page'
weight = 10
[[menu.main]]
name = 'Gallery'
pageRef = '/galleries'
title = 'view the works'
weight = 20
