baseURL = 'https://localhost:5713/'
languageCode = 'en-us'
title = 'Orthopraxis'
theme = 'skeleton'
[params]
subtitle = 'The Art of Paul Brown'

[[menu.main]]
name = 'Home'
pageRef = '/'
title = 'return to home page'
weight = 10
[[menu.main]]
name = 'Gallery'
pageRef = '/galleries'
title = 'view the works'
weight = 20

[[build]]
port = 5713